Add custom cod docs
gojekfarm/vmq-docs pull request #1
Opened 2022-09-23 10:32 UTC by dumbpreacher

2022-09-25 12:02 UTC, dhruvjain99 requested changes

2022-09-25 12:02 UTC, dhruvjain99 commented on README.md
> +- This project provides an option to disable persistence: [no op engine](configuration/noopengine.md)
Can we rename noopengine.md to no-op-engine.md?

2022-09-25 12:02 UTC, dhruvjain99 commented on SUMMARY.md
> +* [MQTT Introduction](Add link here)
Link missing?

2022-09-25 12:02 UTC, dhruvjain99 commented on configuration/routing.md
> +One of the problems that we tried to address was that of routing state not syncing when one of the nodes did was restarted. The subscription state used to build up on other nodes and the restarted no
```suggestion
One of the problems that we tried to address was that of subscription state not syncing when one of the nodes restarted. The subscription state used to build up on other nodes and the restarted node was unable to catch up to the other nodes. We finally achieved this using an external store(redis) for maintaining a common subscription state for all the nodes. 
```

2022-09-25 12:02 UTC, dhruvjain99 commented on configuration/the-vernemq-conf-file.md
> +[Here](Add plugins here)
Plugins missing?

2022-10-03 06:06 UTC, dumbpreacher commented on README.md
> +- This project provides an option to disable persistence: [no op engine](configuration/noopengine.md)
The forked project follows a naming convention where we do not use any delimiters within words.

2022-10-03 06:07 UTC, dumbpreacher commented on configuration/routing.md
> +One of the problems that we tried to address was that of routing state not syncing when one of the nodes did was restarted. The subscription state used to build up on other nodes and the restarted no
Sure.

2022-10-03 06:12 UTC, dumbpreacher commented on configuration/the-vernemq-conf-file.md
> +[Here](Add plugins here)
Added

2022-10-05 13:00 UTC, merged